# Generated by Django 3.2.5 on 2021-07-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Ticket',
        ),
    ]
